fx_version "cerulean"
game "gta5"

name "AB"
description "AB - Generated by CarKit Web"
author "CarKit Web"
version "1.0.0"

client_script "client.lua"

-- Vehicle data files
data_file "HANDLING_FILE" "data/handling.meta"
data_file "VEHICLE_METADATA_FILE" "data/vehicles.meta"
data_file "VEHICLE_VARIATIONS_FILE" "data/carvariations.meta"
data_file "VEHICLE_LAYOUTS_FILE" "data/vehiclelayouts.meta"

-- Vehicle models
files {
    "stream/*.yft",
    "stream/*.ytd",
}

-- Additional data
files {
    "data/vehicles.meta",
    "data/vehiclelayouts.meta",
    "data/handling.meta",
    "data/carvariations.meta",
    "data/maps/shop_vehicle.meta",
    "data/maps/dlctext.meta",
}

-- Spawn codes: AB
