fx_version "cerulean"
game "gta5"

name "defz_demonag"
description "DEFz_demonAG - Generated by CarKit Web"
author "CarKit Web"
version "1.0.0"

client_script "client.lua"

-- Vehicle data files
data_file "HANDLING_FILE" "data/handling.meta"
data_file "VEHICLE_METADATA_FILE" "data/vehicles.meta"
data_file "CARCOLS_FILE" "data/carcols.meta"
data_file "VEHICLE_VARIATIONS_FILE" "data/carvariations.meta"

-- Vehicle models
files {
    "stream/*.yft",
    "stream/*.ytd",
}

-- Additional data
files {
    "data/carcols.meta",
    "data/vehicles.meta",
    "data/handling.meta",
    "data/carvariations.meta",
}

-- Spawn codes: defz_demonag
